### ISSUE TITLE
Publishing posts via the API publishes them as drafts

### ISSUE THREAD

**Issue by sssilver** [writefreely/writefreely#462]
### Describe the bug
When using the post publishing API, the published posts are not really "published", they are posted as drafts. From there, there appears to be no API for publishing a draft post.

### Steps to reproduce (if necessary)
1. Publish a writefreely post using the API
2. Observe the post is created as a draft and is not visible to the public

### Expected behavior
What should've happened?
- The post should have been published, or the API should have supported a flag for publishing it

### Application configuration
 - **Single mode or Multi-user mode?** Single mode
 - **Database?** [mysql/sqlite] sqlite3
 - **Open registration?** [yes/no] no
 - **Federation enabled?** [yes/no] no

**Version or last commit**: latest Docker image

**Comment by thebaer** [comment]
Hi @sssilver, thanks for taking an interest in the WriteFreely API! Things are definitely a bit unconventional, but you can absolutely publish a blog post by hitting the [**Publish a Collection Post**](https://developers.write.as/docs/api/#publish-a-collection-post) endpoint (blogs are internally called "collections"), instead of the [**Publish a Post**](https://developers.write.as/docs/api/#publish-a-post) endpoint.

If you publish a draft first, you'll simply move that draft to a blog / collection with our [**Move a Post**](https://developers.write.as/docs/api/#move-a-post-to-a-collection) endpoint.

I'll close this since it isn't a bug in the software. But if you have any questions, please feel free to join us on [our forum](https://discuss.write.as)!

**Comment by sssilver** [comment]
Thanks, this helps tremendously! Are the docs opensource? Should we amend the documentation to clarify this?

**Comment by thebaer** [comment]
Yes, that'd be great! Please feel free to send a PR here: https://github.com/writeas/api-docs

**Comment by sssilver** [comment]
I got a PR up at https://github.com/writeas/api-docs/pull/7. What's the process for getting it reviewed and merged?

Thanks!
