### ISSUE TITLE
Scheduled posts are not published on ActivityPub?

### ISSUE THREAD

**Issue by matthiasbeyer** [writefreely/writefreely#465]
### Describe the bug

When scheduling a blog post into the future, it does not become available via federation (as soon as the scheduled date is passed), it seems.

### Steps to reproduce (if necessary)
1. Schedule a post in the future
2. Wait for it being published
3. Check via an activity-pub based service (I tried mastodon), it is not visible

### Expected behavior

Post should be published via activitypub as well.

### Application configuration
 - Single mode
 - mysql
 - **Open registration?** no
 - **Federation enabled?** yes

**Version or last commit**:

0.12.0

---

Example:

~~https://beyermatthias.de/iceland-on-top-of-the-world-md should be visible via mastodon, was a scheduled post. But when searching in mastodon (https://mastodon.technology for me) for `beyermatthias.de` and then clicking on the account, the post is not in the history of the account.~~

I just republished the post, so the above is not true anymore.

**Comment by rkingett** [comment]
I can confirm this is a problem. I can duplicate this.

**Comment by thebaer** [comment]
Thanks for the report, @matthiasbeyer. It's true that scheduled post functionality doesn't extend to the fediverse at the moment, but we plan to add this functionality in the future: see [T567](https://writefreely.org/tasks/567).

To keep things organized, I'd like to continue tracking this new feature on that Phabricator task, instead of in a bug report here. So I'll close this for now.
