### ISSUE TITLE
Federation doesn't seem to work

### ISSUE THREAD

**Issue by mkyos** [writefreely/writefreely#472]
Dear developers, hello! My instance's Fediverse doesn't seem to work. Here's what I got when I ran `sudo journalctl -f -u writefreely`:

> Jun 23 02:03:30 ip-x-x-x-x writefreely[1284]: 2021/06/23 02:03:30 "GET /.well-known/webfinger?resource=acct:ulysses@uselessulysses.com" 200 331.515µs "http.rb/4.4.1 (Mastodon/3.4.1; +https://o3o.ca/)"

This report may have occurred when I tried to follow a user in a mastodon. I kept failing. The mastodon gave me an error message: 

> missing_resource: Could not determine the jump URL for your account

By the way, I'm running this **single user** instance on an **EC2 of AWS,** is it possible that the security group's port settings are not able to transfer data for the ActivityPub protocol? I allow all 80 and 443 inbound traffic, and my site was accessed normally.

**Comment by thebaer** [comment]
Hi @mkyos, you'll also need to allow outbound traffic to ensure federation works. Otherwise, do you have `federation = true` in the `[app]` section of your config?

I'm going to close this since I'm assuming it's more of a potential configuration issue than a bug in WriteFreely. But we can reopen if it turns out to be a bug.

Otherwise, please join us on [our forum](https://discuss.write.as/c/writefreely/15) if you have questions about getting set up! GitHub issues are only meant for detailed bug reports that others can replicate.
