### ISSUE TITLE
Self signed certificates required even in reverse-proxy mode

### ISSUE THREAD

**Issue by poVoq** [writefreely/writefreely#481]
### Describe the bug
Despite what the installation tutorial says, I can not start my 0.13 writefreely instance in reverse-proxy mode without first creating the self-signed certificates. 

### Expected behavior
This should either be mentioned in the tutorial, or not be required for reverse-proxy configurations.

**Comment by thebaer** [comment]
Hi @poVoq, which self-signed certificates are you referring to? I'm not able to find anything about that in the instructions.

I'm going to close this since it's more of a configuration / documentation issue than something that belongs in our bug tracker, but please feel free to continue the discussion about this [on our forum](https://discuss.write.as/c/writefreely/installation/16).

**Comment by poVoq** [comment]
Same issue as here on the forum: https://discuss.write.as/t/service-doesnt-start-keys-email-aes256-missing/2434

Unless I do `writefreely keys generate ` the service doesn't start, which is odd given that all certs are handled by Nginx.

**Comment by thebaer** [comment]
Ah, that command generates _encryption keys_ for database data, session cookies, etc. -- it doesn't have anything to do with SSL certificates (self-signed or not).

**Comment by poVoq** [comment]
Ah, my bad then. Might be good to make that more explicit in the installation tutorial though. Thanks!
