### ISSUE TITLE
requesting feature, federated!

### ISSUE THREAD

**Issue by cauerego** [writefreely/writefreely#536]
i rather not create a user on your forums to request a feature.

can't you offer a fediverse link instead?

i will try now @write_as@writing.exchange

**Comment by thebaer** [comment]
Hey, thanks for taking an interest in the project! As we mention, GitHub is only for bugs, and the forum is where we do everything else, so that's the only place to make a feature request if you hope for us to implement it :slightly_smiling_face: You can always log in with your GitHub account, if that helps!

**Comment by cauerego** [comment]
and thanks for the quick reply.

i see you must mean coding bugs only.

to me, this clearly constitutes a technical, ux, and logical bug/issue.

but perhaps i will forever be the only one who sees this. for sure, a better way to communicate will eventually arise, though. i definitely can't rush it. i can only plant small seeds. cheers!
