### ISSUE TITLE
Mardown is not like markdown

### ISSUE THREAD

**Issue by lbm-services** [writefreely/writefreely#611]
I tried to import my rednotebook text files... rednotebook claims to use markdown as well, but here headlines are marked with equation '=', etc. Imported "posts" look like a mess. I guess there are multiple flavours of markdown.

**Comment by thebaer** [comment]
Yes that's true :slightly_smiling_face: 

I'll close this report since it doesn't involve a particular bug within scope of this application. But you might check out these related PRs and discussions:

* #523 
* [Markdown inconsistencies and markdown flavour](https://discuss.write.as/t/markdown-inconsistencies-and-markdown-flavour/750)
