### ISSUE TITLE
First person to register shouldn't be automatically the admin

### ISSUE THREAD

**Issue by shleeable** [writefreely/writefreely#629]
### Describe the bug
First registration is admin.. I'd rather have used the create admin cli function.

I was unable to create a second admin account using the cli.

### Steps to reproduce (if necessary)
Some random was admin of my new writefreely.

### Expected behavior
some random was not the admin of my instance.

**Version or last commit**:
main

**Comment by thebaer** [comment]
Thanks for the feedback. We should definitely make it clearer in the docs that you should always create an account right after installing WriteFreely. I've opened writefreely/documentation#45 to address this.

Otherwise, we're tracking development on support for multiple admins here: [T538](https://writefreely.org/tasks/538).
