### ISSUE TITLE
Arm Support for Version 0.13.2

### ISSUE THREAD

**Issue by moquito64** [writefreely/writefreely#703]
Sorry to bother but I was looking for an Arm version of 0.13.2. I noticed that issue #135 stated that it was going to be supported going forward but Is this no longer the case? I prefer to use official packages versus building from source so this would be greatly appreciated.

**Comment by thebaer** [comment]
There was an issue (#565) with our cross-compiling tool, which is why we didn't put out an Arm version with the last release.

However, that's been fixed, and I'm working toward our next v0.14 release now. I'll be sure to include an Arm version (along with all other platforms we supported before). So if you sit tight, we'll have an official next release out soon!
